server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/revplay/auth/**

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/revplay/catalog/**

        - id: playlist-service
          uri: lb://PLAYLIST-SERVICE
          predicates:
            - Path=/revplay/playlists/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/revplay/analytics/**

        - id: favourites-service
          uri: lb://FAVORITES-SERVICE
          predicates:
            - Path=/revplay/favorites/**

        - id: playback-service
          uri: lb://PLAYBACK-SERVICE
          predicates:
            - Path=/revplay/playback/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.servlet.DispatcherServlet: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,actuator