spring:
  application:
    name: PLAYLIST-SERVICE

  config:
    import: configserver:http://localhost:8888

  profiles:
    active: local

  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 10